name: my_app
description: "3ะบั"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg
    
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/AceSans-Demo.otf
